version: "3.8"

services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${CALIBRE_LIBRARY_PATH}:/books
    ports:
      - 8083:8083
    restart: unless-stopped
